server.port=8899
spring.application.name=spring-ai-deepseek-demo

# deepseek?apiKey
spring.ai.openai.api-key=sk-34f2ac0695224b49ab14c87a3d5f53c5
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.7
