server.port=8899
spring.application.name=spring-ai-deepseek-demo

#spring.ai.dashscope.api-key=sk-026f3ee568f34cc3a237ea27****
spring.ai.dashscope.api-key=sk-ws-H.EXMRXPM.nRVU.MEYCIQDUa4DIZVZ3I4tnrfs8O-QBNAWs_IHMQ-31gNUd4_m_AQIhAMDD9TEeWFdlmfa8aXeOHCqfT_R4hvNIC7QYd5W_VVAY